// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/21/2026, 11:51:29 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/humeditph/Documents/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/humeditph/Documents/portfolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/humeditph/Documents/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/humeditph/Documents/portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/humeditph/Documents/portfolio/plugins/**/*.{js,ts,mjs}","/Users/humeditph/Documents/portfolio/composables/**/*.{js,ts,mjs}","/Users/humeditph/Documents/portfolio/utils/**/*.{js,ts,mjs}","/Users/humeditph/Documents/portfolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/humeditph/Documents/portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/humeditph/Documents/portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/humeditph/Documents/portfolio/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;